x-common: &common
  tty: true
  stdin_open: true

services:
  bean:
    <<: *common
    build:
      context: .
      dockerfile: ./bean/Dockerfile
    env_file:
      - ./bean/config/.env.example
      - ./bean/config/.env
    networks:
      - harvest
    volumes:
      - ./bean:/go/src/bean
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      smtp:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  pear:
    <<: *common
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - harvest
    volumes:
      - ./pear/html:/usr/share/nginx/html
      - ./pear/config/nginx.conf:/etc/nginx/conf.d/default.conf

  smtp:
    <<: *common
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "8025:8025"
    networks:
      - harvest
    volumes:
      - mailhog-data:/var/lib/mailhog

  redis:
    <<: *common
    image: redis:latest
    restart: always
    networks:
      - harvest
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    <<: *common
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bean_test
    networks:
      - harvest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    <<: *common
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - harvest
    volumes:
      - ./shared/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./bean/config/nginx.conf:/etc/nginx/conf.d/bean.conf
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  harvest:
    driver: bridge

volumes:
  mailhog-data:
  redis-data:
  postgres-data:
