x-common: &common
  tty: true
  stdin_open: true

services:
  bean:
    <<: *common
    build:
      context: .
      dockerfile: ./bean/Dockerfile
    env_file:
      - ./bean/config/.env.example
      - ./bean/config/.env
    ports:
      - "8080:8080"
    volumes:
      - ./bean:/go/src/bean
    depends_on:
      postgres:
        condition: service_healthy

  pear:
    <<: *common
    build:
      context: .
      dockerfile: ./pear/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./pear:/go/src/pear

  postgres:
    <<: *common
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bean_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  postgres-data:
