services:
  bean:
    restart: always
    networks:
      - harvest
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  trellis:
    restart: always
    networks:
      - harvest
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  harvest:
    driver: bridge
