x-common: &common
  tty: true
  stdin_open: true

services:
  bean:
    <<: *common
    build:
      context: .
      dockerfile: ./bean/Dockerfile
    env_file:
      - ./bean/config/.env.example
      - ./bean/config/.env
    ports:
      - "8080:8080"
    volumes:
      - ./bean:/go/src/bean
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      smtp:
        condition: service_started

  pear:
    <<: *common
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./pear/html:/usr/share/nginx/html
      - ./pear/config/nginx.conf:/etc/nginx/conf.d/default.conf

  smtp:
    <<: *common
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog-data:/var/lib/mailhog

  redis:
    <<: *common
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 1s
      timeout: 1s
      retries: 5

  postgres:
    <<: *common
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bean_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  postgres-data:
  redis-data:
  mailhog-data:
