# use official go image
FROM golang:1.22.0-alpine

# set working dir
WORKDIR /go/src

# copy monorepo deps
COPY go.mod go.sum ./

# copy bean code
COPY bean/ ./bean/

# get deps : go.mod
RUN go mod download

# get deps : tern (migration, seed)
RUN go install github.com/jackc/tern/v2@latest

# get deps : air (hot reload)
RUN go install github.com/cosmtrek/air@latest

# run boot script
CMD ["bean/bin/boot.dev.sh"]
