# use official nginx image
FROM nginx:1.25-alpine

# copy nginx config
COPY ./nginx.conf /etc/nginx/nginx.conf

# copy dev services 
COPY ./services.dev /etc/nginx/services

# expose port 80
EXPOSE 80
