# use official nginx image
FROM nginx:1.25-alpine

# copy nginx config
COPY ./trellis/nginx.conf /etc/nginx/nginx.conf

# copy prod services 
COPY ./trellis/services.prod /etc/nginx/services

# expose port 80
EXPOSE 80
# expose port 443
EXPOSE 443
